# Generated by Django 5.2.5 on 2025-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aboutdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('best_selling', 'Best Selling'), ('you_may_also_like', 'You May Also Like')], default='new_arrival', max_length=50),
        ),
    ]
