# Generated by Django 5.2.5 on 2025-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('best_selling', 'Best Selling'), ('you_may_also_like', 'You May Also Like'), ('men', 'Shop for Men'), ('women', 'Shop for Women'), ('accessories', 'Shop Accessories')], default='new_arrival', max_length=50),
        ),
    ]
